version: '3'
services:
    mysql_database:
        image: mariadb:latest
        restart: always
        # volumes:
        #   - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
        environment:
            MYSQL_ROOT_PASSWORD: testRootPassword
        command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306